version: "3.9"

services:
  app_pr:
    container_name: app_pr
    image: app_pr:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
